//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chaithit_Market.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_electric
    {
        public int id { get; set; }
        public string group_name { get; set; }
        public string dns_meter { get; set; }
        public Nullable<decimal> value { get; set; }
        public Nullable<System.DateTime> value_datetime { get; set; }
        public string status_text_en { get; set; }
    }
}
